version: '3'
services:
    ors-build:
        build:
            context: ../
            args:
                APP_CONFIG: ./docker/conf/app.config.lisboa
        volumes:
            - ./build/:/ors-core/build/
    ors-core:
        container_name: ors-core
        ports:
            - 8080:8080
        image: "tomcat:8-jre8"
        volumes:
            - ./build/:/usr/local/tomcat/webapps/
            - ./data/:/usr/local/tomcat/data/
            - ./logs/ors/:/var/log/ors/
            - ./logs/tomcat/:/usr/local/tomcat/logs
            - ./conf/catalina.properties:/usr/local/tomcat/conf/catalina.properties
        environment:
            - JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g
        depends_on: 
            - ors-build
